const QUESTS = [
  {key:"hero",short:"主人公",reward:"主人公の種",title:"主人公の核を見つける",enemy:"ぼんやりの霧",time:"約5分",dialogue:"上手に説明しなくて大丈夫。まずは、心が動く主人公を一人だけ連れてこよう。",prompt:"どんな人物・生き物を描きたい？ 見た目だけでなく、その人らしさが伝わる言葉をひとつ添えてみて。",placeholder:"例：雨音を集めて旅する、少し臆病な魔法使いの少女",suggestions:["小さな竜を守る少年","記憶をなくした星の旅人","古い森で暮らす白い狐","雨音を瓶に集める魔法使い","影だけが成長しない少女","壊れた機械を治す旅人","人の夢に迷い込む黒猫","最後の星を探す天文学者","名前を持たない森の番人","月明かりで手紙を書く幽霊"]},
  {key:"emotion",short:"感情",reward:"心のしずく",title:"感情を仕草に変える",enemy:"無表情の壁",time:"約5分",dialogue:"感情は、顔だけじゃなく手や姿勢にも隠れている。静かな動きを一つ選ぼう。",prompt:"主人公はいま何を感じていて、それがどんな仕草に表れている？",placeholder:"例：不安を隠すように、濡れた手紙を胸元で強く握っている",suggestions:["期待に目を細める","寂しさに肩をすぼめる","決意して一歩を踏み出す","不安を隠して袖を握る","安心して小さく息を吐く","驚いて言葉を失う","怒りをこらえて拳をほどく","大切なものを胸に抱える","遠くを見つめて微笑む","涙をぬぐわず空を見上げる"]},
  {key:"moment",short:"一瞬",reward:"物語の欠片",title:"物語の一瞬を選ぶ",enemy:"設定だけの沼",time:"約6分",dialogue:"世界の説明より、物語が動く一秒を切り取ると絵は息を始めるよ。",prompt:"描くのは、何かが起こる直前・最中・直後のどの瞬間？ 場所と出来事を一文にしてみよう。",placeholder:"例：夜明け前の駅で、届くはずのない返事が風に乗って現れた瞬間",suggestions:["扉を開ける直前","再会して名前を呼ぶ瞬間","嵐が去り光が差す直後","届かないはずの手紙を見つけた瞬間","初めて魔法が光を放った瞬間","列車が夜空へ走り出す直前","約束の場所に一人でたどり着いた直後","眠っていた街の時計が動き出す瞬間","敵だった相手が手を差し出した瞬間","最後の灯りを次の人へ渡す直前"]},
  {key:"visual",short:"演出",reward:"演出の羅針盤",title:"構図・光・小物を決める",enemy:"棒立ちの回廊",time:"約7分",dialogue:"ここからは演出。カメラの距離、光、小さな象徴を一つずつ置いていこう。",prompt:"どこから見た構図？ 光はどこから？ 物語を象徴する小物を一つ入れるなら？",placeholder:"例：少し見下ろす全身構図、窓から青い朝の光、足元に壊れた懐中時計",suggestions:["顔に寄る／逆光／花びら","背中から／夕暮れ／古い鍵","遠景／月明かり／赤い傘","少し見下ろす／朝の光／懐中時計","低い視点／稲妻／割れた剣","真横から／窓明かり／一通の手紙","俯瞰／星明かり／小さなランタン","手元に寄る／木漏れ日／青い羽根","広角／霧の逆光／足跡","正面から／ろうそくの光／銀の指輪"]},
  {key:"style",short:"仕上げ",reward:"世界の光",title:"世界の手触りを決める",enemy:"なんとなく生成",time:"約7分",dialogue:"最後は世界の手触り。あなたが見たい色と質感を選べば、生成文が完成する。",prompt:"色合い・画材や質感・空気感はどうしたい？ 好きな作品の雰囲気を言葉で表してもOK。",placeholder:"例：くすんだ青紫と金、透明感のある水彩、夢から覚める直前の静けさ",suggestions:["淡い水彩と朝もや","深い青と金の映画的な光","鉛筆線とやわらかな紙の質感","黒紫と銀、星屑のきらめき","くすんだ暖色と古い絵本の質感","白と水色、ガラスのような透明感","鮮やかなネオンと雨上がりの反射","深い緑と琥珀、静かな森の湿度","モノクロに赤だけを残した緊張感","桃色の夕焼けとフィルム写真の粒子"]}
];

const STORAGE_KEY="iris-mini-quest-v4", LEGACY_KEY="iris-mini-quest-v3";
const QUEST_IMAGES=[
  {src:"assets/quest-1-origin.webp",alt:"魔法の本から主人公の可能性が生まれる幻想的な場面",caption:"まだ名前のない物語"},
  {src:"assets/quest-2-emotion.webp",alt:"二つの手が光る心を包み、感情が仕草へ変わる場面",caption:"言葉になる前の気持ち"},
  {src:"assets/quest-3-moment.webp",alt:"夜明け前の駅に不思議な手紙が現れる物語の一瞬",caption:"物語が動き出す一秒"},
  {src:"assets/quest-4-directing.webp",alt:"鍵や羅針盤と月光で構図を決める魔法の演出台",caption:"光と視線を導くもの"},
  {src:"assets/quest-5-world.webp",alt:"五つの創作の欠片が一つの幻想世界になる場面",caption:"あなたの世界の入口"}
];
const ENEMY_IMAGES=[
  {src:"assets/enemy-fog.webp",alt:"黒紫の霧でできた小さな敵"},
  {src:"assets/enemy-mask.webp",alt:"ひび割れた白い仮面の敵"},
  {src:"assets/enemy-swamp.webp",alt:"巻物と蔦をまとった紫色のスライムの敵"},
  {src:"assets/enemy-pose.webp",alt:"不自然な姿勢で固まった木偶騎士の敵"},
  {src:"assets/enemy-vague.webp",alt:"結晶の欠片が揺らぐ一つ目の敵"}
];
const initialState={current:0,answers:{},complete:false,started:false,completedAt:null};
let state=loadState(), transitionTimer;
const suggestionDecks={}, suggestionViews={};
const $=id=>document.getElementById(id);
const elements={introPanel:$("introPanel"),journeyArea:$("journeyArea"),startButton:$("startButton"),savedJourneyActions:$("savedJourneyActions"),resumeButton:$("resumeButton"),introResetButton:$("introResetButton"),progressCount:$("progressCount"),progressFill:$("progressFill"),mapNodes:$("mapNodes"),questCard:$("questCard"),dialogue:$("dialogue"),questNumber:$("questNumber"),timeEstimate:$("timeEstimate"),enemy:$("enemy"),enemyMeter:$("enemyMeter"),enemyActor:$("enemyActor"),enemyImage:$("enemyImage"),questImage:$("questImage"),questImageNumber:$("questImageNumber"),questImageCaption:$("questImageCaption"),questTitle:$("questTitle"),questPrompt:$("questPrompt"),suggestionArea:$("suggestionArea"),suggestions:$("suggestions"),suggestionRound:$("suggestionRound"),answerInput:$("answerInput"),characterCount:$("characterCount"),inputHint:$("inputHint"),backButton:$("backButton"),hintButton:$("hintButton"),nextButton:$("nextButton"),inventory:$("inventory"),saveStatus:$("saveStatus"),resetButton:$("resetButton"),finalPanel:$("finalPanel"),finalPrompt:$("finalPrompt"),copyButton:$("copyButton"),downloadButton:$("downloadButton"),editButton:$("editButton"),newJourneyButton:$("newJourneyButton"),achievementToast:$("achievementToast"),achievementText:$("achievementText")};

function loadState(){try{const current=JSON.parse(localStorage.getItem(STORAGE_KEY));if(current)return{...initialState,...current,answers:current.answers||{}};const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY));if(legacy){const migrated={...initialState,...legacy,answers:legacy.answers||{},started:true};localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated}}catch(error){console.warn("保存データを読み込めませんでした。",error)}return{...initialState,answers:{}}}
function saveState(showPulse=false){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(showPulse){elements.saveStatus.classList.add("saved");setTimeout(()=>elements.saveStatus.classList.remove("saved"),700)}}
function answeredCount(){return QUESTS.filter(q=>Boolean(state.answers[q.key]?.trim())).length}
function createInventoryItem(q){const item=document.createElement("div");item.className=`inventory-item${state.answers[q.key]?" filled":""}`;const icon=document.createElement("span");icon.className="inventory-icon";icon.textContent=state.answers[q.key]?"✦":"·";const copy=document.createElement("div"),label=document.createElement("small"),answer=document.createElement("p");label.textContent=q.short;answer.textContent=state.answers[q.key]||"まだ見つかっていません";copy.append(label,answer);item.append(icon,copy);return item}
function renderMap(){elements.mapNodes.replaceChildren(...QUESTS.map((q,index)=>{const node=document.createElement("div");node.className="map-node";if(state.answers[q.key])node.classList.add("complete");if(!state.complete&&index===state.current)node.classList.add("active");const dot=document.createElement("span"),label=document.createElement("span");dot.className="map-dot";dot.textContent=state.answers[q.key]?"✓":String(index+1);label.textContent=q.short;node.append(dot,label);return node}))}
function render(){const answered=answeredCount();elements.progressCount.textContent=`${answered} / ${QUESTS.length}`;elements.progressFill.style.width=`${answered/QUESTS.length*100}%`;renderMap();elements.inventory.replaceChildren(...QUESTS.map(createInventoryItem));if(!state.started){const hasSavedProgress=answered>0;elements.introPanel.hidden=false;elements.journeyArea.hidden=true;elements.finalPanel.hidden=true;elements.startButton.hidden=hasSavedProgress;elements.savedJourneyActions.hidden=!hasSavedProgress;return}elements.introPanel.hidden=true;if(state.complete){elements.finalPrompt.textContent=buildPrompt();elements.finalPanel.hidden=false;elements.journeyArea.hidden=true;return}elements.journeyArea.hidden=false;elements.finalPanel.hidden=true;const q=QUESTS[state.current],art=QUEST_IMAGES[state.current],foe=ENEMY_IMAGES[state.current];elements.dialogue.textContent=q.dialogue;elements.questNumber.textContent=`QUEST ${state.current+1} / ${QUESTS.length}`;elements.timeEstimate.textContent=q.time;elements.enemy.textContent=q.enemy;elements.enemyMeter.style.width="100%";elements.enemyActor.className="enemy-actor";elements.enemyActor.setAttribute("aria-label",`敵：${q.enemy}`);elements.enemyImage.src=foe.src;elements.enemyImage.alt=foe.alt;elements.questImage.src=art.src;elements.questImage.alt=art.alt;elements.questImageNumber.textContent=`CHAPTER ${String(state.current+1).padStart(2,"0")}`;elements.questImageCaption.textContent=art.caption;elements.questTitle.textContent=q.title;elements.questPrompt.textContent=q.prompt;elements.answerInput.placeholder=q.placeholder;elements.answerInput.value=state.answers[q.key]||"";updateEnemyReaction();updateCharacterCount();elements.inputHint.textContent="";elements.backButton.disabled=state.current===0;elements.nextButton.innerHTML=state.current===QUESTS.length-1?'生成文を完成させる <span>✦</span>':'この言葉で進む <span>→</span>';elements.suggestionArea.hidden=true;elements.suggestions.replaceChildren();elements.hintButton.textContent="迷ったら候補を見る";if(QUEST_IMAGES[state.current+1])new Image().src=QUEST_IMAGES[state.current+1].src;if(ENEMY_IMAGES[state.current+1])new Image().src=ENEMY_IMAGES[state.current+1].src;replayQuestEntrance()}
function replayQuestEntrance(){elements.questCard.classList.remove("is-entering");void elements.questCard.offsetWidth;elements.questCard.classList.add("is-entering")}
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function nextSuggestions(q){if(!suggestionDecks[q.key]||suggestionDecks[q.key].length<3)suggestionDecks[q.key]=shuffle(q.suggestions);return suggestionDecks[q.key].splice(0,3)}
function renderSuggestionChoices(q){const choices=nextSuggestions(q);const total=Math.ceil(q.suggestions.length/3);suggestionViews[q.key]=((suggestionViews[q.key]||0)%total)+1;elements.suggestions.replaceChildren(...choices.map(text=>{const button=document.createElement("button");button.className="suggestion";button.type="button";button.setAttribute("aria-pressed","false");button.textContent=text;button.addEventListener("click",()=>{elements.suggestions.querySelectorAll("button").forEach(candidate=>candidate.setAttribute("aria-pressed","false"));button.setAttribute("aria-pressed","true");elements.answerInput.value=text;updateDraft(true);elements.answerInput.focus()});return button}));elements.suggestionRound.textContent=`${suggestionViews[q.key]} / ${total}`}
function updateCharacterCount(){elements.characterCount.textContent=`${elements.answerInput.value.length} / 240`}
function updateEnemyReaction(){const hasAnswer=Boolean(elements.answerInput.value.trim());elements.enemyActor.classList.toggle("weakened",hasAnswer);elements.enemyMeter.style.width=hasAnswer?"38%":"100%"}
function updateDraft(showPulse=false){const value=elements.answerInput.value.trim();if(value)state.answers[QUESTS[state.current].key]=value;else delete state.answers[QUESTS[state.current].key];saveState(showPulse);updateCharacterCount();updateEnemyReaction();elements.inputHint.textContent=""}
function commitCurrent(){updateDraft(true);if(!state.answers[QUESTS[state.current].key]){elements.inputHint.textContent="一言でも大丈夫。候補を選ぶか、思いついた言葉を置いてみよう。";elements.answerInput.focus();elements.answerInput.classList.add("has-error");setTimeout(()=>elements.answerInput.classList.remove("has-error"),700);return false}return true}
function buildPrompt(){const a=state.answers;return `【描きたい一枚】\n${a.hero}。\n\n【感情と仕草】\n${a.emotion}。\n\n【物語の瞬間】\n${a.moment}。\n\n【構図・光・象徴】\n${a.visual}。\n\n【色・質感・空気感】\n${a.style}。\n\n人物の感情が伝わる自然なポーズ、物語性のある一場面、丁寧な光と奥行き。上記の意図を保ちながら、画面全体に一貫した世界観を持たせる。`}
function showAchievement(text,callback){clearTimeout(transitionTimer);elements.achievementText.textContent=text;elements.achievementToast.hidden=false;requestAnimationFrame(()=>elements.achievementToast.classList.add("visible"));transitionTimer=setTimeout(()=>{elements.achievementToast.classList.remove("visible");setTimeout(()=>{elements.achievementToast.hidden=true;callback?.()},220)},850)}
function beginJourney(resume=false){if(!resume&&answeredCount()===0)state.current=0;state.started=true;state.complete=false;saveState();render();$("questArea").scrollIntoView({behavior:"smooth",block:"start"})}

elements.startButton.addEventListener("click",()=>beginJourney(answeredCount()>0));elements.resumeButton.addEventListener("click",()=>beginJourney(true));
elements.nextButton.addEventListener("click",()=>{if(!commitCurrent())return;const q=QUESTS[state.current];elements.nextButton.disabled=true;elements.enemyMeter.style.width="0%";elements.enemyActor.classList.add("defeated");showAchievement(q.reward,()=>{elements.nextButton.disabled=false;if(state.current<QUESTS.length-1){state.current++;saveState();render();$("questArea").scrollIntoView({behavior:"smooth",block:"start"})}else{state.complete=true;state.completedAt=new Date().toISOString();saveState();render();elements.finalPanel.scrollIntoView({behavior:"smooth",block:"start"})}})});
elements.backButton.addEventListener("click",()=>{updateDraft();state.current=Math.max(0,state.current-1);saveState();render()});
elements.hintButton.addEventListener("click",()=>{renderSuggestionChoices(QUESTS[state.current]);elements.suggestionArea.hidden=false;elements.hintButton.textContent="別の候補を見る";elements.enemyActor.classList.add("startled");setTimeout(()=>elements.enemyActor.classList.remove("startled"),520)});
elements.answerInput.addEventListener("input",()=>updateDraft());elements.answerInput.addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&event.key==="Enter"){event.preventDefault();elements.nextButton.click()}});
elements.copyButton.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(buildPrompt());elements.copyButton.textContent="コピーしました ✓"}catch{elements.copyButton.textContent="コピーできませんでした"}setTimeout(()=>{elements.copyButton.textContent="生成文をコピー"},1800)});
elements.downloadButton.addEventListener("click",()=>{const blob=new Blob([buildPrompt()],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="わたしのAI創作プロンプト.txt";anchor.click();URL.revokeObjectURL(url)});
elements.editButton.addEventListener("click",()=>{state.complete=false;state.current=QUESTS.length-1;saveState();render()});
function resetJourney(){if(!confirm("保存されている答えを消して、はじめから進みますか？"))return;state={...initialState,answers:{}};localStorage.removeItem(LEGACY_KEY);saveState();render();scrollTo({top:0,behavior:"smooth"})}
elements.resetButton.addEventListener("click",resetJourney);elements.introResetButton.addEventListener("click",resetJourney);elements.newJourneyButton.addEventListener("click",resetJourney);render();
